backend: 
  name: github
  branch: master 
  repo: raoufswe/my-blog-gatsby

media_folder: static/img
public_folder: /img

collections: 
  - name: "post"
    label: "Post"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      